// TDD Skeleton for module: unity-adapters
// Spec: .claude/tdd/specs/unity-adapters.spec.md
// Generated by tdd_gen — fill in test implementations

using Xunit;

public class UnityAdaptersTests
{
    [Fact]
    public void UnityAssetGatewayHappyPath()
    {
        Assert.True(false, "TODO: implement happy path for UnityAssetGateway");
    }

    [Fact]
    public void InMemoryAssetGatewayHappyPath()
    {
        Assert.True(false, "TODO: implement happy path for InMemoryAssetGateway");
    }

    [Fact]
    public void UnityFileSystemInMemoryFileSystemHappyPath()
    {
        Assert.True(false, "TODO: implement happy path for UnityFileSystem / InMemoryFileSystem");
    }

}
